### ISSUE TITLE
Getting Unhandled Rejection Request 

### ISSUE THREAD

**Issue by ErraticFox** [corasan/leagueoflegends-node-api#1]
Hello, I'm following the example here and am getting a Unhandled Rejection Request. 

Error: 
```js
Error: getaddrinfo ENOTFOUND na.api.pvp.net na.api.pvp.net:443
    at new RequestError (C:\Users\errat\Desktop\test\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\errat\Desktop\test\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\errat\Desktop\test\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\errat\Desktop\test\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\errat\Desktop\test\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by corasan** [comment]
That's probably because Riot changed the API URLs to a more recent version. I'll look into it when I have a bit of time to update it. Thanks for reporting!

**Comment by ErraticFox** [comment]
Yeah, I do see that. Quite a lot of their url has changed and moved around. I'm going to try and fix it for you and I'll submit it for your review. :)

EDIT: It looks like they've also recategorized a lot of things. If you want, I can go through and redo them and categorize like they have them here on the left side: https://developer.riotgames.com/api-methods/

It would be easier to reference to the documents on what's where.

**Comment by corasan** [comment]
I would really appreciate it! I am pretty busy right now so I can't take the time to do all that.

Thanks! 👍
